spring:
  application:
    name: WRService
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        jta:
          platform: org.hibernate.engine.transaction.internal.jta.JtaPlatformStandardImpl
    open-in-view: false